# Site settings
title: Yatan Blumenthal Vargas
tag_text: Yatan Blumenthal Vargast
description: Hello! I’m Yatan. I work on brain health, decentralized science, and building communities that help new ideas grow.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
